---
- name: Create change request
  servicenow.itsm.change_request:
    instance:
      host: "{{ snow_credentials.instance | default(snow_instance, true)}}"
      username: "{{ snow_credentials.username | default(snow_username, true)}}"
      password: "{{ snow_credentials.password | default(snow_password, true)}}"
    type: standard
    state: new
    requested_by: some.user
    short_description: "GitOps Change: Update for {{ app_name }} on {{ target_clusters }}"
    description: "{{ change_request.description }}"
    priority: "{{ change_request.priority }}"
    risk: low
    impact: low
  register: new_incident

- debug:
    var: new_incident
